# Generated by Django 5.1.2 on 2024-11-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoria",
            name="imagen",
            field=models.ImageField(
                default="", upload_to="pasajes", verbose_name="imagen"
            ),
        ),
    ]
